# Fish completion for fpasoterm. Install with: fpasoterm --completion fish | source

complete -c fpasoterm -s h -l help -d 'Show help'
complete -c fpasoterm -s v -l version -d 'Show version and build commit'
complete -c fpasoterm -l update-check -d 'Compare installed version with npm latest'
complete -c fpasoterm -l doctor -d 'Check updates, npm audit, and config health'
complete -c fpasoterm -s l -l list -d 'List running windows'
complete -c fpasoterm -s q -l close -r -d 'Close a PID, exact title, or all'
complete -c fpasoterm -l broadcast -r -d 'Send text to local windows'
complete -c fpasoterm -l broadcast-target -r -d 'Limit Broadcast targets'
complete -c fpasoterm -l broadcast-sync -d 'Include the sync channel'
complete -c fpasoterm -s d -l dev -d 'Rebuild local debug binary'
complete -c fpasoterm -s F -l foreground -d 'Keep launcher attached'
complete -c fpasoterm -s C -l console-diagnostics -d 'Print diagnostics to stderr'
complete -c fpasoterm -s c -l config -r -F -d 'Use a config.toml file'
complete -c fpasoterm -s p -l profile -r -d 'Apply a named profile'
complete -c fpasoterm -l profile-list -d 'List named profiles'
complete -c fpasoterm -l show-config -d 'Print resolved config'
complete -c fpasoterm -l config-check -d 'Validate config'
complete -c fpasoterm -l config-path -d 'Print config path'
complete -c fpasoterm -l config-example -d 'Print config example'
complete -c fpasoterm -l diagnostics -d 'Print diagnostics report'
complete -c fpasoterm -l open-log-dir -d 'Open terminal log directory'
complete -c fpasoterm -l copy-diagnostics -d 'Copy diagnostics report'
complete -c fpasoterm -l plugin-list -d 'List local User/plugins files'
complete -c fpasoterm -l plugin-path -d 'Print plugin directory'
complete -c fpasoterm -l plugin-info -r -d 'Show plugin information'
complete -c fpasoterm -l plugin-uninstall -r -d 'Remove local plugin files'
complete -c fpasoterm -l plugin-search -d 'Search official public plugin ports'
complete -c fpasoterm -l plugin-install -r -a 'terminal/hello terminal/welcome-banner terminal/status-banner terminal/theme appearance/amber appearance/teal appearance/high-contrast productivity/git-status productivity/session-marker' -d 'Download an official public port'
complete -c fpasoterm -l plugin-ports-dir -r -F -d 'Install --plugin-install from this local checkout'
complete -c fpasoterm -l plugin-install-file -r -F -d 'Copy a trusted local .js/.ts plugin'
complete -c fpasoterm -l force -d 'Replace an existing plugin during install'
complete -c fpasoterm -l enable -d 'Enable a plugin installed by an install command'
complete -c fpasoterm -l enable-plugin -r -d 'Enable plugins'
complete -c fpasoterm -l disable-plugin -r -d 'Disable plugins'
complete -c fpasoterm -l plugin-enable -r -d 'Alias for enable-plugin'
complete -c fpasoterm -l plugin-disable -r -d 'Alias for disable-plugin'
complete -c fpasoterm -l plugin-enable-all -d 'Enable all discovered plugins'
complete -c fpasoterm -l plugin-disable-all -d 'Disable all plugins'
complete -c fpasoterm -l update-config -d 'Add missing config defaults'
complete -c fpasoterm -l prune-config -d 'Remove unsupported config settings'
complete -c fpasoterm -l setup-sync -d 'Configure a sync folder'
complete -c fpasoterm -l sync-status -d 'Show sync health'
complete -c fpasoterm -l sync-clean -d 'Remove expired sync commands'
complete -c fpasoterm -l sync-diagnostics -d 'Print sync diagnostics'
complete -c fpasoterm -l self-update -d 'Update an npm installation'
complete -c fpasoterm -l self-update-checkout -d 'Update a git checkout'
complete -c fpasoterm -l update-desktop -d 'Refresh desktop integration'
complete -c fpasoterm -s s -l shell -r -d 'Override shell'
complete -c fpasoterm -s e -l command -r -d 'Run command after launch'
complete -c fpasoterm -s t -l title -r -d 'Override titlebar title'
complete -c fpasoterm -s b -l titlebar-color -r -d 'Override titlebar color'
complete -c fpasoterm -s r -l reset-window-state -d 'Delete saved window size'
complete -c fpasoterm -s R -l reset-config -d 'Restore default config'
complete -c fpasoterm -s W -l width -r -d 'Override window width'
complete -c fpasoterm -s H -l height -r -d 'Override window height'
complete -c fpasoterm -s z -l size -r -d 'Override window size'
complete -c fpasoterm -s k -l debug-keys -d 'Enable key diagnostics'
complete -c fpasoterm -l x11 -d 'Use the X11 GTK backend'
complete -c fpasoterm -l debug-opaque-terminal -d 'Use opaque terminal background'
complete -c fpasoterm -l disable-dmabuf -d 'Disable Linux DMA-BUF renderer'
complete -c fpasoterm -l completion -r -a 'bash zsh fish powershell' -d 'Print completion script'
complete -c fpasoterm -l completion-install -r -a 'bash zsh fish powershell' -d 'Install persistent completion'
complete -c fpasoterm -l completion-uninstall -r -a 'bash zsh fish powershell' -d 'Remove persistent completion'
